on: workflow_dispatch

env:
  JENKINS_HOST: http://184.72.163.189/ ## jenkins base url
  JENKINS_JOB: test_github_actions_job ## builds the HelloWorld job inside testJobs

jobs:
  launch_jenkins_job:
    name: trigger jenkins job
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST "http://184.72.163.189:8080/job/test_github_actions_job/build" --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}"
